package crypto

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"math/big"
	"testing"
	"time"
)

// makeCertKey builds a self-signed certificate plus its EC private key, and a
// fullchain that optionally appends extra (distinct) CA certificates.
func makeCertKey(t *testing.T, cn string, extraCA int) (certPEM, fullchainPEM, keyPEM []byte) {
	t.Helper()
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatalf("gen key: %v", err)
	}
	serial, _ := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 128))
	tmpl := &x509.Certificate{
		SerialNumber: serial,
		Subject:      pkix.Name{CommonName: cn},
		DNSNames:     []string{cn},
		NotBefore:    time.Now().Add(-time.Hour),
		NotAfter:     time.Now().Add(90 * 24 * time.Hour),
		KeyUsage:     x509.KeyUsageDigitalSignature | x509.KeyUsageKeyEncipherment,
		ExtKeyUsage:  []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
	}
	der, err := x509.CreateCertificate(rand.Reader, tmpl, tmpl, &key.PublicKey, key)
	if err != nil {
		t.Fatalf("create cert: %v", err)
	}
	certPEM = pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der})
	fullchainPEM = append([]byte{}, certPEM...)
	for i := 0; i < extraCA; i++ {
		caCN := cn + "-ca"
		caKey, _ := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
		caTmpl := &x509.Certificate{
			SerialNumber:          big.NewInt(int64(1000 + i)),
			Subject:               pkix.Name{CommonName: caCN},
			NotBefore:             time.Now().Add(-time.Hour),
			NotAfter:              time.Now().Add(365 * 24 * time.Hour),
			IsCA:                  true,
			BasicConstraintsValid: true,
			KeyUsage:              x509.KeyUsageCertSign,
		}
		caDER, err := x509.CreateCertificate(rand.Reader, caTmpl, caTmpl, &caKey.PublicKey, caKey)
		if err != nil {
			t.Fatalf("create ca: %v", err)
		}
		fullchainPEM = append(fullchainPEM, pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: caDER})...)
	}
	keyDER, err := x509.MarshalECPrivateKey(key)
	if err != nil {
		t.Fatalf("marshal key: %v", err)
	}
	keyPEM = pem.EncodeToMemory(&pem.Block{Type: "EC PRIVATE KEY", Bytes: keyDER})
	return certPEM, fullchainPEM, keyPEM
}

// T32: PickCertPEM must be deterministic and prefer fullchain.
func TestPickCertPEM_Deterministic(t *testing.T) {
	certPEM, fullchainPEM, keyPEM := makeCertKey(t, "pick.example.com", 2)
	files := map[string][]byte{
		"cert.pem":      certPEM,
		"fullchain.pem": fullchainPEM,
		"privkey.pem":   keyPEM,
		"cert.pfx":      []byte("dummy"),
	}
	first := PickCertPEM(files)
	if first == nil {
		t.Fatal("PickCertPEM returned nil")
	}
	for i := 0; i < 200; i++ {
		if got := PickCertPEM(files); string(got) != string(first) {
			t.Fatalf("iteration %d: PickCertPEM is not deterministic", i)
		}
	}
	if string(first) != string(fullchainPEM) {
		t.Error("PickCertPEM must prefer fullchain.pem when present")
	}

	// Without fullchain it must fall back to a certificate (never the key),
	// deterministically.
	delete(files, "fullchain.pem")
	second := PickCertPEM(files)
	if string(second) != string(certPEM) {
		t.Errorf("fallback should pick cert.pem, got %d bytes", len(second))
	}
	for i := 0; i < 200; i++ {
		if got := PickCertPEM(files); string(got) != string(second) {
			t.Fatalf("iteration %d: fallback is not deterministic", i)
		}
	}

	// Only a key present → nil (must not return the private key).
	only := map[string][]byte{"privkey.pem": keyPEM}
	if got := PickCertPEM(only); got != nil {
		t.Error("PickCertPEM must not return a private key")
	}
}

// T25: Modern (PBES2/AES-256) containers generated by this package must decode.
func TestParsePFXLeafChain_ModernAndLegacy(t *testing.T) {
	certPEM, fullchainPEM, keyPEM := makeCertKey(t, "pfx.example.com", 2)

	wantChain := ParseCertChainPEM(fullchainPEM)
	if len(wantChain) != 3 {
		t.Fatalf("expected 3 certs in fullchain, got %d", len(wantChain))
	}

	for _, tc := range []struct {
		name   string
		encode func([]byte, []byte, string) ([]byte, error)
	}{
		{"legacy", GeneratePFX},
		{"modern", GeneratePFXModern},
	} {
		pfx, err := tc.encode(fullchainPEM, keyPEM, "testpw")
		if err != nil {
			t.Fatalf("%s: encode: %v", tc.name, err)
		}
		leaf, ca, err := ParsePFXLeafChain(pfx, "testpw")
		if err != nil {
			t.Fatalf("%s: ParsePFXLeafChain: %v", tc.name, err)
		}
		if leaf == nil {
			t.Fatalf("%s: nil leaf", tc.name)
		}
		if string(leaf.Raw) != string(wantChain[0].Raw) {
			t.Errorf("%s: leaf mismatch", tc.name)
		}
		if len(ca) != 2 {
			t.Errorf("%s: caCerts = %d, want 2 (DecodeChain must return the chain)", tc.name, len(ca))
		}
		// Wrong password must be classified, not silently accepted.
		if _, _, err := ParsePFXLeafChain(pfx, "wrongpw"); err == nil {
			t.Errorf("%s: wrong password must fail", tc.name)
		} else if ClassifyPFXError(err) == "" {
			t.Errorf("%s: ClassifyPFXError returned empty for %v", tc.name, err)
		}
	}

	// A leaf-only PFX (cert.pem source) legitimately carries no CA certs.
	leafOnly, err := GeneratePFX(certPEM, keyPEM, "testpw")
	if err != nil {
		t.Fatalf("leaf-only encode: %v", err)
	}
	if _, ca, err := ParsePFXLeafChain(leafOnly, "testpw"); err != nil || len(ca) != 0 {
		t.Errorf("leaf-only PFX: err=%v caCerts=%d, want 0", err, len(ca))
	}
}
